version: '3.8'

services:

  matching_service:
    build:
      context: .
      dockerfile: src/MatchingService/MatchingService.Api/Dockerfile

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8084
      ConnectionStrings__MatchingServiceDb: ${MATCHING_DB_CONNECTION}
      OpenRouteService__ApiKey: ${OPENROUTESERVICE_API_KEY}

    container_name: matching_service

    ports:
      - "8084:8084"

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - swiftride-network


  mysql:
    image: mysql:8.4

    container_name: swiftride_mysql

    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: swiftride_matching

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-p123456"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - swiftride-network


networks:
  swiftride-network:
    driver: bridge


volumes:
  mysql_data: